<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Contractor;
use AppBundle\Entity\Timetable;
use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function getContractorTimetablePayments(Contractor $contractor, Timetable $timetable): array
    {
        $qb = $this->createQueryBuilder('payment');
        $startDate = clone $timetable->getCreated()->modify('first day of');
        $endDate = clone $timetable->getCreated()->modify('last day of');

        $qb
            ->andWhere($qb->expr()->gte('payment.date', ':start_date'))
            ->andWhere($qb->expr()->lte('payment.date', ':end_date'))
            ->andWhere($qb->expr()->eq('payment.contractor', ':contractor'))
            ->setParameters([
                'start_date' => $startDate,
                'end_date' => $endDate,
                'contractor' => $contractor
            ])
        ;

        return $qb->getQuery()->getResult();
    }
}
