<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Timetable;

/**
 * TimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetableRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastOrCreateTable()
    {
        $timetable = $this->findOneBy([], ['id' => 'DESC']);

        if (!$timetable) {
            $em = $this->getEntityManager();

            $timetable = new Timetable();
            $timetable->setName(sprintf('Табель %s', date('m.Y')));

            $em->persist($timetable);
            $em->flush();
        }

        return $timetable;
    }

    /**
     * @param Timetable $timetable
     * @return array
     */
    public function getAllPrevious(Timetable $timetable)
    {
        $qb = $this->createQueryBuilder('timetable');

        $qb
            ->where($qb->expr()->lte('timetable.id', ':id'))
            ->setParameter('id', $timetable)
        ;

        return $qb->getQuery()->getResult();
    }
}
