<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Contractor;
use AppBundle\Entity\Timetable;
use AppBundle\Entity\TimetableRow;
use AppBundle\Entity\TimetableRowTimes;
use Doctrine\ORM\EntityRepository;

/**
 * TimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetableRowTimesRepository extends EntityRepository
{
    /**
     * @param TimetableRow $timetableRow
     * @return TimetableRowTimes
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function getTimesOrCreate(TimetableRow $timetableRow): TimetableRowTimes
    {
        $times = $this->findOneBy([
            'timetableRow' => $timetableRow,
        ]);

        if (!$times) {
            $em = $this->getEntityManager();

            $times = new TimetableRowTimes();
            $times->setTimetableRow($timetableRow);

            $em->persist($times);
            $em->flush($times);
        }

        return $times;
    }

    public function calculateContractorBalance(Timetable $timetable, Contractor $contractor)
    {
        $em = $this->getEntityManager();

        $timetables = $em->getRepository('AppBundle:Timetable')->getAllPrevious($timetable);

        $criteria = [
            'timetable' => $timetables,
            $contractor->getType() => $contractor
        ];

        $timetableRows = $em->getRepository('AppBundle:TimetableRow')->findBy($criteria);

        $timetableRowTimes = $this->findBy([
            'timetableRow' => $timetableRows,
        ]);

        $total = 0;

        /** @var TimetableRowTimes $timetableRowTime */
        foreach ($timetableRowTimes as $timetableRowTime) {
            $timetableRow = $timetableRowTime->getTimetableRow();
            $sumTimes = $this->sumTimes($timetableRowTime->getTimes());

            if ($contractor->getType() == Contractor::PROVIDER) {
                $total += ($timetableRow->getPriceForProvider() * $sumTimes);
            } else {
                $total += ($timetableRow->getPriceForCustomer() * $sumTimes);
            }
        }

        return $total;
    }

    /**
     * @param array $times
     * @return int
     */
    public function sumTimes(array $times)
    {
        $sumTimes = 0;
        foreach ($times as $time) {
            $sumTimes += (int) $time;
        }

        return $sumTimes;
    }
}
