<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Timetable;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ContractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getManagersByFio(Timetable $timetable, $roles = ['ROLE_CUSTOMER_MANAGER', 'ROLE_RENT_MANAGER']): array
    {
        $qb = $this->getManagerQueryBuilder($roles);

        $subQb = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->from('AppBundle:TimetableRow', 'timetable_row_1')
            ->select('manager.id')
            ->join('timetable_row_1.manager', 'manager')
            ->where($qb->expr()->eq('timetable_row_1.timetable', ':timetable'))
        ;

        $subQb2 = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->from('AppBundle:TimetableRow', 'timetable_row_2')
            ->select('provider_manager.id')
            ->join('timetable_row_2.providerManager', 'provider_manager')
            ->where($qb->expr()->eq('timetable_row_2.timetable', ':timetable'))
        ;

        $qb
            ->andWhere($qb->expr()->orX(
                $qb->expr()->in('entity.id', $subQb->getDQL()),
                $qb->expr()->in('entity.id', $subQb2->getDQL())
            ))
            ->setParameter('timetable', $timetable)
        ;

        $managers = $qb->getQuery()->getResult();

        $managersByFio = [];
        /** @var User $manager */
        foreach ($managers as $manager) {
            $managersByFio[$manager->getAbbrFullName()] = $manager->getFullName();
        }

        return $managersByFio;
    }

    public function getManagersById($roles = ['ROLE_CUSTOMER_MANAGER', 'ROLE_RENT_MANAGER']): array
    {
        $managers = $this->getManagers($roles);

        $managersById = [];
        /** @var User $manager */
        foreach ($managers as $manager) {
            $managersById[$manager->getId()] = $manager->getAbbrFullName();
        }

        return $managersById;
    }

    public function getManagers($role = ['ROLE_CUSTOMER_MANAGER']): array
    {
        return
            $this->getManagerQueryBuilder($role)
            ->addOrderBy('entity.lastname', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function getManagerQueryBuilder($roles = ['ROLE_CUSTOMER_MANAGER']): QueryBuilder
    {
        $qb = $this->createQueryBuilder('entity');

        $orX = $qb->expr()->orX();
        foreach ($roles as $i => $role) {
            $orX->add($qb->expr()->like('entity.roles', ':roles'.$i));
            $qb->setParameter('roles'.$i, '%'.$role.'%');
        }

        return $qb->andWhere($orX);
    }
}
