services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    timetable.helper:
        class: AppBundle\Service\TimetableHelper
        arguments: ['@doctrine.orm.entity_manager']