services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    acme.twig.acme_extension:
        class: AppBundle\Twig\TimetableExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }