services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    timetable.helper:
        class: AppBundle\Service\TimetableHelper
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.authorization_checker'
            - '@request_stack'
            - '@router'
    report.helper:
            class: AppBundle\Service\ReportHelper
            arguments:
                - '@doctrine.orm.entity_manager'
                - '@timetable.helper'
                - '@security.authorization_checker'
                - '@security.token_storage'
                - '@router'
    acme.twig.acme_extension:
        class: AppBundle\Twig\TimetableExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }